"""
Fake data returned when DEMO_MODE=true.
Matches the JSON shapes produced by the ic_metrics dbt mart.
"""

MOCK_TEAMS = [
    {"id": "aaaaaaaa-0001-0001-0001-aaaaaaaaaaaa", "name": "Engineering"},
    {"id": "bbbbbbbb-0002-0002-0002-bbbbbbbbbbbb", "name": "Member Support"},
]

MOCK_TEAM_MEMBERS = [
    {
        "id": "11111111-1111-1111-1111-111111111111",
        "username": "Alex Rivera",
        "team": "Engineering",
        "github_data": [
            {
                "pr_id": 101,
                "pr_title": "feat: add OAuth2 login flow",
                "pr_number": 42,
                "github_username": "alex-rivera",
                "github_repo_name": "acme-org/platform",
                "branch_name": "feat/oauth2-login",
                "created_at": "2026-03-28T09:12:00Z",
                "days_active": 7,
                "is_draft": False,
                "is_merged": False,
                "is_closed_unmerged": False,
                "github_author_association": "MEMBER",
                "github_assignee_login": "alex-rivera",
            },
            {
                "pr_id": 102,
                "pr_title": "chore: upgrade dependencies",
                "pr_number": 43,
                "github_username": "alex-rivera",
                "github_repo_name": "acme-org/platform",
                "branch_name": "chore/dep-upgrades",
                "created_at": "2026-04-01T14:00:00Z",
                "days_active": 3,
                "is_draft": True,
                "is_merged": False,
                "is_closed_unmerged": False,
                "github_author_association": "MEMBER",
                "github_assignee_login": None,
            },
        ],
        "freshdesk_data": [],
        "active_sprint_points": 8,
        "asana_data": [
            {
                "task_id": "1001",
                "name": "Design system audit",
                "completed": False,
                "days_active": 12,
                "due_on": "2026-04-10",
                "priority": "High",
                "sprint_points": 5,
            },
            {
                "task_id": "1002",
                "name": "Write integration tests for data pipeline",
                "completed": False,
                "days_active": 4,
                "due_on": "2026-04-07",
                "priority": "Medium",
                "sprint_points": 3,
            },
        ],
    },
    {
        "id": "22222222-2222-2222-2222-222222222222",
        "username": "Jordan Kim",
        "team": "Engineering",
        "github_data": [
            {
                "pr_id": 201,
                "pr_title": "fix: resolve race condition in job scheduler",
                "pr_number": 17,
                "github_username": "jordan-kim",
                "github_repo_name": "acme-org/workers",
                "branch_name": "fix/scheduler-race",
                "created_at": "2026-04-02T11:30:00Z",
                "days_active": 2,
                "is_draft": False,
                "is_merged": False,
                "is_closed_unmerged": False,
                "github_author_association": "MEMBER",
                "github_assignee_login": "jordan-kim",
            },
        ],
        "freshdesk_data": [],
        "active_sprint_points": 8,
        "asana_data": [
            {
                "task_id": "2001",
                "name": "Migrate legacy ETL to dlt",
                "completed": False,
                "days_active": 21,
                "due_on": "2026-04-15",
                "priority": "Urgent",
                "sprint_points": 8,
            },
        ],
    },
    {
        "id": "33333333-3333-3333-3333-333333333333",
        "username": "Morgan Patel",
        "team": "Member Support",
        "github_data": [],
        "freshdesk_data": [
            {
                "ticket_id": 5001,
                "ticket_subject": "Cannot log in after password reset",
                "status": 2,
                "priority": 3,
                "days_active": 2,
                "created_at": "2026-04-02T08:45:00Z",
                "updated_at": "2026-04-03T10:00:00Z",
                "due_by_date": "2026-04-05T17:00:00Z",
            },
            {
                "ticket_id": 5002,
                "ticket_subject": "Data export missing last 2 weeks",
                "status": 6,
                "priority": 4,
                "days_active": 5,
                "created_at": "2026-03-30T13:00:00Z",
                "updated_at": "2026-04-01T09:30:00Z",
                "due_by_date": "2026-04-04T17:00:00Z",
            },
            {
                "ticket_id": 5003,
                "ticket_subject": "Request for additional user seats",
                "status": 3,
                "priority": 2,
                "days_active": 1,
                "created_at": "2026-04-03T15:20:00Z",
                "updated_at": "2026-04-03T15:20:00Z",
                "due_by_date": None,
            },
        ],
        "asana_data": [],
        "active_sprint_points": 0,
    },
    {
        "id": "44444444-4444-4444-4444-444444444444",
        "username": "Sam Okonkwo",
        "team": "Member Support",
        "github_data": [],
        "freshdesk_data": [
            {
                "ticket_id": 5010,
                "ticket_subject": "Bulk import failing for CSV > 10k rows",
                "status": 2,
                "priority": 4,
                "days_active": 8,
                "created_at": "2026-03-27T10:00:00Z",
                "updated_at": "2026-04-02T14:00:00Z",
                "due_by_date": "2026-04-06T17:00:00Z",
            },
        ],
        "asana_data": [
            {
                "task_id": "4001",
                "name": "Update onboarding documentation",
                "completed": False,
                "days_active": 3,
                "due_on": "2026-04-09",
                "priority": "Low",
                "sprint_points": 2,
            },
        ],
        "active_sprint_points": 2,
    },
]
