services:
  web-app:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.app
    ports:
      - "5000:5000"
    env_file:
      - .local/local.env
    environment:
      - DB_DRIVER=postgresql
      - DB_HOST=docker.host.internal
      - DB_PORT=5432
      - DB_NAME=tmcadmin
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
