services:
  web-app:
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.app
    ports:
      - "5000:5000"
    env_file:
      - .local/local.env
    environment:
      - DB_HOST=host.docker.internal
