name: pulse

profile: pulse

model-paths: ['models']
macro-paths: ['macros']
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  pulse:
    +materialized: table
    00_base:
      +materialized: view
      +schema: base
    01_staging:
      +schema: staging
    02_marts:
