FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./

RUN pip install --no-cache-dir uv
RUN uv sync --group pipeline --group development --no-install-project

COPY ./src/data_pipeline ./src/data_pipeline
COPY ./src/common ./src/common

RUN cd src/data_pipeline/analytics && uv run dbt deps

CMD ["uv", "run", "src/data_pipeline/run_pipeline.py", "--docker"]