"""add friendly_name

Revision ID: f4bec94a57f5
Revises: f60702cc174d
Create Date: 2026-05-27 11:08:22.262881

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4bec94a57f5"
down_revision: Union[str, Sequence[str], None] = "f60702cc174d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("maintenance_shifts", "id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "maintenance_shifts", "team_member_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "maintenance_shifts", "start_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "maintenance_shifts", "end_date", existing_type=sa.DATE(), nullable=False
    )
    op.create_foreign_key(
        None, "maintenance_shifts", "team_members", ["team_member_id"], ["id"]
    )
    op.add_column(
        "sprint_period", sa.Column("friendly_name", sa.String(length=80), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sprint_period", "friendly_name")
    op.drop_constraint(None, "maintenance_shifts", type_="foreignkey")
    op.alter_column(
        "maintenance_shifts", "end_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "maintenance_shifts", "start_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "maintenance_shifts", "team_member_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column("maintenance_shifts", "id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
