"""add username

Revision ID: b54d61b8d61b
Revises: 2bf505c44976
Create Date: 2026-04-03 21:55:13.670756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b54d61b8d61b"
down_revision: Union[str, Sequence[str], None] = "2bf505c44976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_members", sa.Column("user_name", sa.String(length=80), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_members", "user_name")
    # ### end Alembic commands ###
