"""drop user id

Revision ID: 4490a6a0ed5b
Revises: cd6a929880bb
Create Date: 2026-04-03 22:06:44.701147

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4490a6a0ed5b"
down_revision: Union[str, Sequence[str], None] = "cd6a929880bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("team_members_user_id_fkey"), "team_members", type_="foreignkey"
    )
    op.drop_column("team_members", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_members",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("team_members_user_id_fkey"), "team_members", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
