"""fill out team member info

Revision ID: 2bf505c44976
Revises: 2003ac400242
Create Date: 2026-04-03 14:13:25.913229

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bf505c44976"
down_revision: Union[str, Sequence[str], None] = "2003ac400242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_members",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "team_members",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "team_members", sa.Column("github_fk", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "team_members", sa.Column("asana_fk", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "team_members", sa.Column("freshdesk_fk", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "modified_at")
    op.drop_column("users", "created_at")
    op.drop_column("team_members", "freshdesk_fk")
    op.drop_column("team_members", "asana_fk")
    op.drop_column("team_members", "github_fk")
    op.drop_column("team_members", "modified_at")
    op.drop_column("team_members", "created_at")
    # ### end Alembic commands ###
