"""add sprint period model

Revision ID: f60702cc174d
Revises: 3b6b3ab58923
Create Date: 2026-05-27 10:59:22.271893

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f60702cc174d"
down_revision: Union[str, Sequence[str], None] = "3b6b3ab58923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sprint_period",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "maintenance_shifts", "start_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "maintenance_shifts", "end_date", existing_type=sa.DATE(), nullable=False
    )
    op.drop_column("maintenance_shifts", "end_time")
    op.drop_column("maintenance_shifts", "start_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "maintenance_shifts",
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "maintenance_shifts",
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "maintenance_shifts", "end_date", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "maintenance_shifts", "start_date", existing_type=sa.DATE(), nullable=True
    )
    op.drop_table("sprint_period")
    # ### end Alembic commands ###
