"""add team_member_sprint

Revision ID: c8dd7e3b043a
Revises: f4bec94a57f5
Create Date: 2026-06-25 08:49:55.809067

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8dd7e3b043a"
down_revision: Union[str, Sequence[str], None] = "f4bec94a57f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_member_sprint",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_member_id", sa.Uuid(), nullable=False),
        sa.Column("sprint_period_id", sa.Uuid(), nullable=False),
        sa.Column("working_days", sa.Integer(), nullable=False, system_default=10),
        sa.Column(
            "is_on_maintenance", sa.Boolean(), nullable=False, system_default=False
        ),
        sa.ForeignKeyConstraint(
            ["sprint_period_id"],
            ["sprint_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_member_id"],
            ["team_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_member_sprint")
    # ### end Alembic commands ###
