"""add maintenance shift

Revision ID: 3b6b3ab58923
Revises: 0e031f0d6057
Create Date: 2026-04-16 08:38:40.916570

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b6b3ab58923"
down_revision: Union[str, Sequence[str], None] = "0e031f0d6057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_shifts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_member_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_member_id"],
            ["team_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "team_members", "active", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team_members", "active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_table("maintenance_shifts")
    # ### end Alembic commands ###
