"""add active flag

Revision ID: 0e031f0d6057
Revises: 4490a6a0ed5b
Create Date: 2026-04-03 22:23:51.352774

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e031f0d6057"
down_revision: Union[str, Sequence[str], None] = "4490a6a0ed5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_members", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_members", "active")
    # ### end Alembic commands ###
