pulse:
  target: production
  outputs:
    # Run against CloudSQL
    production:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USERNAME') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | as_number}}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt_dev
    
    # Run against local PG
    local:
      type: postgres
      host: "localhost"
      user: "dev"
      password: "823"
      port: 5432
      dbname: "tmcadmin"
      schema: dbt_dev

