# name: dbt CI

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]
#     paths:
#       - "src/data-pipeline/analytics/**"

# jobs:
#   dbt-compile:
#     if: github.event.pull_request.draft == false
#     runs-on: ubuntu-latest
#     name: Compile

#     defaults:
#       run:
#         working-directory: src/data-pipeline/analytics

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v44
#         with:
#           files: |
#             src/data-pipeline/analytics/**

#       - name: Set up Python
#         if: steps.changed-files.outputs.any_changed == 'true'
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install uv
#         if: steps.changed-files.outputs.any_changed == 'true'
#         uses: astral-sh/setup-uv@v4

#       - name: Install dependencies
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv sync

#       - name: Install dbt packages
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv run dbt deps

#       - name: Compile dbt project
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv run dbt compile --profiles-dir .
#         env:
#           DBT_TARGET: dev

#   dbt-test:
#     if: github.event.pull_request.draft == false
#     runs-on: ubuntu-latest
#     name: Tests
#     needs: dbt-compile

#     defaults:
#       run:
#         working-directory: src/data-pipeline/analytics

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v44
#         with:
#           files: |
#             src/data-pipeline/analytics/**

#       - name: Set up Python
#         if: steps.changed-files.outputs.any_changed == 'true'
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install uv
#         if: steps.changed-files.outputs.any_changed == 'true'
#         uses: astral-sh/setup-uv@v4

#       - name: Install dependencies
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv sync

#       - name: Install dbt packages
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv run dbt deps

#       - name: Run dbt tests
#         if: steps.changed-files.outputs.any_changed == 'true'
#         run: uv run dbt test --profiles-dir .
#         env:
#           DBT_TARGET: dev
